# Generated by Django 2.2.6 on 2019-12-06 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime
import wellness.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resistanceType', models.CharField(max_length=20, validators=[wellness.models.validate_resistance_type])),
                ('distance', models.FloatField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('reps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=50)),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('birthAssignedSex', models.CharField(max_length=10, validators=[wellness.models.validate_birth_sex])),
                ('currentSex', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('location', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.User')),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('resistanceType', models.CharField(max_length=20, validators=[wellness.models.validate_resistance_type])),
                ('weight', models.FloatField()),
                ('repsPerSet', models.IntegerField()),
                ('compound', models.BooleanField(default=False)),
                ('primaryMuscleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='primaryMuscle', to='wellness.MuscleGroup')),
                ('secondaryMuscleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondaryMuscle', to='wellness.MuscleGroup')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.Workout')),
            ],
        ),
    ]
